#define OR                               1
#define AND                              2
#define BOR                              3
#define BXOR                             4
#define BAND                             5
#define NEQ                              6
#define EQ                               7
#define GT                               8
#define GTE                              9
#define LT                              10
#define LTE                             11
#define SR                              12
#define SL                              13
#define SUB                             14
#define SUM                             15
#define MOD                             16
#define DIV                             17
#define MULT                            18
#define INC                             19
#define DEC                             20
#define NOT                             21
#define BNOT                            22
#define ELSE                            23
#define INTCAST                         24
#define FLOATCAST                       25
#define LPAR                            26
#define RPAR                            27
#define END                             28
#define PROGRAM                         29
#define VAR                             30
#define COMMA                           31
#define ID                              32
#define PRINT                           33
#define PRINTS                          34
#define FREE                            35
#define IF                              36
#define THEN                            37
#define WHILE                           38
#define DO                              39
#define UNTIL                           40
#define REPEAT                          41
#define BREAK                           42
#define CONTINUE                        43
#define FUNCTION                        44
#define CALLBACK                        45
#define ASGN                            46
#define LBRK                            47
#define RBRK                            48
#define CALL                            49
#define NEW                             50
#define STR                             51
#define INTEGER                         52
#define FLOAT                           53
